export const projectId = "gausloelinoodcppxbpa";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhdXNsb2VsaW5vb2RjcHB4YnBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUyMjczNDUsImV4cCI6MjEwMDgwMzM0NX0.D5YMln-BAxK69ttbzEmzJFAgs1J3fveBexonGpuz7KY";
